---
# tasks file for ansible-role-mysql

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ mysql_log_dir }}"
    mode: 0755
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    state: directory
  notify: Restart mysql

- name: Create db directory
  file:
    path: "{{ mysql_db_dir }}"
    mode: 0755
    owner: "{{ mysql_user }}"
    group: "{{ mysql_group }}"
    state: directory
  notify: Restart mysql

- name: Create mysql.conf
  template:
    src: mysql.conf.j2
    dest: "{{ mysql_conf_file }}"
    validate: echo %s
  notify: Restart mysql

- name: Start mysql
  service:
    name: "{{ mysql_service }}"
    enabled: true
    state: started
