---
# since MySQL version i-dont-know, mysql_install_db add --random-passwords
# option, which creates random passwords at ${HOME}/.mysql_secret, usually,
# /root/.mysql_secret. tasks in this file update the random password to
# mysql_login_password.

- name: See if mysql_default_random_password_file exists
  ansible.builtin.stat:
    path: "{{ mysql_default_random_password_file }}"
  register:
    __register_mysql_reset_password_random_stat

- name: Assert mysql_default_random_password_file exists
  assert:
    that:
      - __register_mysql_reset_password_random_stat.stat
      - __register_mysql_reset_password_random_stat.stat.exists

- name: Create SQL to update random password to mysql_login_password (reset-password-random.yml)
  set_fact:
    update_password_sql: "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('{{ mysql_login_password }}');"
  no_log: "{% if mysql_debug %}no{% else %}yes{% endif %}"

- name: Remove comments from /root/.mysql_secret
  ansible.builtin.lineinfile:
    path: "{{ mysql_default_random_password_file }}"
    state: absent
    # XXX the file contains comments
    regexp: "^#.*"

- debug:
    msg: "{{ lookup('file', '/root/.mysql_secret') }}"

- name: Reset mysql_login_password of mysql_login_user (reset-password-random.yml)
  # XXX use mysql CLI to update password.
  #
  # community.mysql.mysql_user does not seem to support expired password.
  #
  # TODO use tempfile to avoid password in command arguments
  ansible.builtin.command: "mysql --user=root --password={{ lookup('file', mysql_default_random_password_file) | quote }} --connect-expired-password --execute {{ update_password_sql | quote }}"

- name: Delete mysql_default_random_password_file
  ansible.builtin.file:
    path: "{{ mysql_default_random_password_file }}"
    state: absent
