---

- name: Reset mysql_login_password of mysql_login_user (reset-password-empty.ym)
  mysql_user:
    name: "{{ mysql_login_user }}"
    password: "{{ mysql_login_password }}"
    login_unix_socket: "{{ mysql_socket_file }}"
